'use strict';

module.exports = {
	// Possible Errors
	'no-loss-of-precision': 'error',
	'no-unreachable-loop': 'error',

	// Best Practices
	'accessor-pairs': 'error',
	'array-callback-return': 'error',
	'class-methods-use-this': 'error',
	'default-case': 'error',
	'default-case-last': 'error',
	'default-param-last': 'error',
	'dot-location': ['error', 'property'],
	'eqeqeq': ['error', 'smart'],
	'grouped-accessor-pairs': ['error', 'getBeforeSet'],
	'guard-for-in': 'error',
	'no-caller': 'error',
	'no-constructor-return': 'error',
	'no-empty-function': 'error',
	'no-eval': 'error',
	'no-extend-native': 'error',
	'no-extra-bind': 'error',
	'no-floating-decimal': 'error',
	'no-implied-eval': 'error',
	'no-invalid-this': 'error',
	'no-iterator': 'error',
	'no-labels': 'error',
	'no-lone-blocks': 'error',
	'no-loop-func': 'error',
	'no-multi-spaces': 'error',
	'no-multi-str': 'error',
	'no-new': 'error',
	'no-new-func': 'error',
	'no-new-wrappers': 'error',
	'no-param-reassign': 'error',
	'no-proto': 'error',
	'no-return-assign': ['error', 'always'],
	'no-return-await': 'error',
	'no-self-compare': 'error',
	'no-sequences': 'error',
	'no-throw-literal': 'error',
	'no-unmodified-loop-condition': 'error',
	'no-unused-expressions': 'error',
	'no-useless-call': 'error',
	'no-useless-return': 'error',
	'no-void': 'error',
	'no-warning-comments': 'warn',
	'prefer-promise-reject-errors': 'error',
	'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
	'radix': 'error',
	'require-await': 'error',
	'wrap-iife': ['error', 'inside'],
	'yoda': 'error',

	// Strict Mode
	'strict': ['error', 'global'],

	// Variables
	'no-undef-init': 'error',
	'no-unused-vars': ['error', { caughtErrors: 'all' }], // @override
	'no-use-before-define': 'error',

	// Stylistic Issues
	'array-bracket-spacing': 'error',
	'block-spacing': 'error',
	'brace-style': ['error', '1tbs', { allowSingleLine: true }],
	'comma-spacing': 'error',
	'comma-style': 'error',
	'computed-property-spacing': 'error',
	'eol-last': 'error',
	'func-call-spacing': 'error',
	'function-call-argument-newline': ['error', 'consistent'],
	'implicit-arrow-linebreak': 'error',
	'indent': ['error', 'tab', { SwitchCase: 1 }],
	'keyword-spacing': 'error',
	'max-statements-per-line': 'error',
	'new-cap': 'error',
	'new-parens': 'error',
	'no-array-constructor': 'error',
	'no-lonely-if': 'error',
	'no-mixed-operators': 'error',
	'no-multi-assign': 'error',
	'no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0, maxBOF: 0 }],
	'no-negated-condition': 'error',
	'no-nested-ternary': 'error',
	'no-new-object': 'error',
	'no-tabs': ['error', { allowIndentationTabs: true }],
	'no-trailing-spaces': 'error',
	'no-underscore-dangle': 'error',
	'no-unneeded-ternary': ['error', { defaultAssignment: false }],
	'no-whitespace-before-property': 'error',
	'nonblock-statement-body-position': 'error',
	'object-curly-spacing': ['error', 'always'],
	'one-var': ['error', { initialized: 'never' }],
	'operator-assignment': 'error',
	'padded-blocks': ['error', 'never'],
	'prefer-exponentiation-operator': 'error',
	'prefer-object-spread': 'error',
	'quote-props': ['error', 'consistent-as-needed'],
	'quotes': ['error', 'single', { avoidEscape: true }],
	'semi': 'error',
	'semi-spacing': 'error',
	'semi-style': 'error',
	'space-before-blocks': 'error',
	'space-before-function-paren': ['error', { anonymous: 'never', named: 'never' }],
	'space-in-parens': 'error',
	'space-infix-ops': 'error',
	'space-unary-ops': 'error',
	'spaced-comment': ['error', 'always', { block: { balanced: true } }],
	'switch-colon-spacing': 'error',
	'template-tag-spacing': 'error',
	'unicode-bom': 'error',

	// ECMAScript 6
	'arrow-spacing': 'error',
	'no-duplicate-imports': 'error',
	'no-useless-computed-key': ['error', { enforceForClassMembers: true }],
	'no-useless-constructor': 'error',
	'no-useless-rename': 'error',
	'no-var': 'error',
	'object-shorthand': ['error', 'always', { avoidExplicitReturnArrows: true }],
	'prefer-const': 'error',
	'prefer-numeric-literals': 'error',
	'prefer-rest-params': 'error',
	'prefer-spread': 'error',
	'rest-spread-spacing': 'error',
	'template-curly-spacing': 'error',
};
